-- SafeTalk realtime schema
-- This script is designed for Supabase Postgres.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
    id uuid primary key default gen_random_uuid(),
    user_id text not null unique,
    name text not null,
    age integer default 0,
    family_role text default 'FILHO',
    profile_status text default 'ATIVO',
    role text default 'CHILD',
    photo_uri text,
    login_identifier text,
    parent_pin text,
    family_code text,
    monitoring_enabled boolean default true,
    funny_filter_enabled boolean default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    user_id text not null,
    name text not null,
    phone text,
    relationship text,
    relationship_type text not null default 'EXTERNAL',
    is_approved_by_parent boolean default false,
    safety_status text default 'PENDENTE',
    is_online boolean default false,
    last_seen text default 'Online',
    unread_count integer default 0,
    avatar_color bigint default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    user_id text not null,
    contact_id bigint not null,
    sender text not null,
    text text,
    media_type text default 'TEXT',
    media_uri text,
    media_duration_seconds integer default 0,
    formatted_time text not null default '00:00',
    delivered boolean default false,
    synced_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.family_groups (
    id bigint generated by default as identity primary key,
    user_id text not null,
    group_name text not null,
    description text default '',
    creator_name text not null,
    creator_role text default 'CHILD',
    created_by_parent boolean default false,
    approval_status text default 'PENDING_PARENT',
    member_count integer default 1,
    is_active boolean default false,
    created_at timestamptz not null default now()
);

create table if not exists public.group_invites (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    user_id text not null,
    invitee_name text not null,
    invited_by text not null,
    requires_parent_approval boolean default true,
    approval_status text default 'PENDING_PARENT',
    created_at timestamptz not null default now()
);

create index if not exists idx_profiles_user_id on public.profiles (user_id);
create index if not exists idx_contacts_user_id on public.contacts (user_id);
create index if not exists idx_messages_user_contact on public.chat_messages (user_id, contact_id);
create index if not exists idx_group_invites_user on public.group_invites (user_id);

alter table public.profiles enable row level security;
alter table public.contacts enable row level security;
alter table public.chat_messages enable row level security;
alter table public.family_groups enable row level security;
alter table public.group_invites enable row level security;

create policy "profiles are viewable by owner"
on public.profiles
for select
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "profiles are insertable by owner"
on public.profiles
for insert
with check (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "profiles are updatable by owner"
on public.profiles
for update
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "contacts are viewable by owner"
on public.contacts
for select
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "contacts are insertable by owner"
on public.contacts
for insert
with check (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "contacts are updatable by owner"
on public.contacts
for update
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "messages are viewable by owner"
on public.chat_messages
for select
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "messages are insertable by owner"
on public.chat_messages
for insert
with check (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "messages are updatable by owner"
on public.chat_messages
for update
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "groups are viewable by owner"
on public.family_groups
for select
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "groups are insertable by owner"
on public.family_groups
for insert
with check (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "groups are updateable by owner"
on public.family_groups
for update
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "invites are viewable by owner"
on public.group_invites
for select
using (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "invites are insertable by owner"
on public.group_invites
for insert
with check (auth.uid()::text = user_id or auth.role() = 'service_role');

create policy "invites are updateable by owner"
on public.group_invites
for update
using (auth.uid()::text = user_id or auth.role() = 'service_role');

alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.contacts;
alter publication supabase_realtime add table public.chat_messages;
alter publication supabase_realtime add table public.family_groups;
alter publication supabase_realtime add table public.group_invites;

create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger profiles_updated_at
before update on public.profiles
for each row execute procedure public.handle_updated_at();

create trigger contacts_updated_at
before update on public.contacts
for each row execute procedure public.handle_updated_at();
